### ISSUE TITLE
Bag file

### ISSUE THREAD

**Issue by ov-vo** [chbloca/yolo_object_discrimination_slam#1]
Hello, I am very interested in your project and hope to reproduce your project. But I don't have an experimental platform. Can you provide some bag files or links? Thanks.

**Comment by christenbc** [comment]
Good night sir, excuse my late answer, it is been a while since I do not log in in GitHub.
Here you go, hope it is somehow useful.
BR.

https://1drv.ms/u/s!AiywCUbmDwSohd8dSivaeC9nC7wB4g?e=jRpyPJ
